### ISSUE TITLE
error running your train.py

### ISSUE THREAD

**Issue by GitZinger** [nsalminen/HMDRemoval#2]
tensorflow 1.7.0 (recommended in the repo homepage, but in your paper, you said 1.15.0 confused which one I should use. Could you give me a conda list the env packages for me to replicate?)

```
Traceback (most recent call last):
  File "train.py", line 76, in <module>
    tf_checkpoint_path = tf.train.Saver(vggface_weights).save(sess, f.name)
  File "C:\Users\Anaconda3\envs\oldertensor\lib\site-packages\tensorflow\python\training\saver.py", line 1311, in __init__
    self.build()
  File "C:\Users\Anaconda3\envs\oldertensor\lib\site-packages\tensorflow\python\training\saver.py", line 1320, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Users\Anaconda3\envs\oldertensor\lib\site-packages\tensorflow\python\training\saver.py", line 1345, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save
```

also

`tf.set_random_seed(int(slurm_id))` wrong. slurm_id is nonetype

I have to add
```
  if slurm_id is None: #added
	     slurm_id = 256  #added
```

p.s. is there a way to reduce your data size/scale( like can I just half of the data but is there a pair or relation among the input, ref and mask in term of name or something?) or set the parameters properly(reduce to 1 gpu or just cpu) to a smaller one so that I can just run it shorter rather than 2.5 days that you mentioned in your paper?

@nsalminen

**Comment by nsalminen** [comment]
Thank you for raising this GitZinger! I overlooked the points you mentioned regarding the TensorFlow version and slurm ID when preparing the code for release. I pushed changes to address this.

With regards your mention of the data size or scale, you could consider resizing the images to a lower resolution. This will significantly reduce training time.

Please let me know if you have any further questions.

**Comment by GitZinger** [comment]
@nsalminen 
Thank you so much for your patience.
1. what if there is only one gpu, does `ng.train.MultiGPUTrainer()` still work with it?
2. right now. I got OOM and then it just crashes:
and I set the `inpaint.yml` to limit the resource to avoid depletion
```
num_gpus_per_job: 1 # number of gpus each job need
num_cpus_per_job: 1 # number of gpus each job need
num_hosts_per_job: 1
memory_per_job: 1 # number of gpus each job need
batch_size: 5

```
and I only used very small scale your data..

but error goes

```
\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[20,512,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients_19/gan_identity_loss_4/model_1/conv3_3_1x1_increase/bn/FusedBatchNormV3_grad/FusedBatchNormGradV3 (defined at C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[Mean_23/_581]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[20,512,28,28] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node gradients_19/gan_identity_loss_4/model_1/conv3_3_1x1_increase/bn/FusedBatchNormV3_grad/FusedBatchNormGradV3 (defined at C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'gradients_19/gan_identity_loss_4/model_1/conv3_3_1x1_increase/bn/FusedBatchNormV3_grad/FusedBatchNormGradV3':
  File "train.py", line 175, in <module>
    log_dir=FLAGS.log_dir,
  File "D:\HMDRemoval\neuralgym\neuralgym\train\multigpu_trainer.py", line 25, in __init__
    super().__init__(**self.context)
  File "D:\HMDRemoval\neuralgym\neuralgym\train\trainer.py", line 38, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "D:\HMDRemoval\neuralgym\neuralgym\train\multigpu_trainer.py", line 78, in train_ops_and_losses
    grads = optimizer.compute_gradients(loss, var_list)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\training\optimizer.py", line 512, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gradients_impl.py", line 158, in gradients
    unconnected_gradients)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 679, in _GradientsHelper
    lambda: grad_fn(op, *out_grads))
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 350, in _MaybeCompile
    return grad_fn()  # Exit early
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gradients_util.py", line 679, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\nn_grad.py", line 926, in _FusedBatchNormV3Grad
    return _BaseFusedBatchNormGrad(op, 2, *grad)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\nn_grad.py", line 890, in _BaseFusedBatchNormGrad
    return grad_fun(**args)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 4360, in fused_batch_norm_grad_v3
    is_training=is_training, name=name)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

...which was originally created as op 'gan_identity_loss_4/model_1/conv3_3_1x1_increase/bn/FusedBatchNormV3', defined at:
  File "train.py", line 175, in <module>
    log_dir=FLAGS.log_dir,
[elided 1 identical lines from previous traceback]
  File "D:\HMDRemoval\neuralgym\neuralgym\train\trainer.py", line 38, in __init__
    self._train_op, self._loss = self.train_ops_and_losses()
  File "D:\HMDRemoval\neuralgym\neuralgym\train\multigpu_trainer.py", line 75, in train_ops_and_losses
    gpu_id=gpu, **graph_def_kwargs)
  File "train.py", line 20, in multigpu_graph_def
    FLAGS, images, masks, references, identity_model, FLAGS, summary=True, reuse=True
  File "D:\HMDRemoval\inpaint_model.py", line 240, in build_graph_with_losses
    identity_model, complete_x1_rgb, complete_x2_rgb, ref_rgb
  File "D:\HMDRemoval\neuralgym\neuralgym\ops\gan_ops.py", line 103, in gan_identity_loss
    complete_add_16 = model(complete_preprocessed)
  File "C:\.conda\envs\tf115\lib\site-packages\keras\engine\base_layer.py", line 489, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\.conda\envs\tf115\lib\site-packages\keras\engine\network.py", line 583, in call
    output_tensors, _, _ = self.run_internal_graph(inputs, masks)
  File "C:\.conda\envs\tf115\lib\site-packages\keras\engine\network.py", line 740, in run_internal_graph
    layer.call(computed_tensor, **kwargs))
  File "C:\.conda\envs\tf115\lib\site-packages\keras\layers\normalization.py", line 185, in call
    epsilon=self.epsilon)
  File "C:\.conda\envs\tf115\lib\site-packages\keras\backend\tensorflow_backend.py", line 2315, in normalize_batch_in_training
    epsilon=epsilon)
  File "C:\.conda\envs\tf115\lib\site-packages\keras\backend\tensorflow_backend.py", line 2288, in _fused_normalize_batch_in_training
    data_format=tf_data_format)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\nn_impl.py", line 1501, in fused_batch_norm
    name=name)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\ops\gen_nn_ops.py", line 4620, in fused_batch_norm_v3
    name=name)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "C:\.conda\envs\tf115\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
```

any idea what may cause this? what can be done to fix this resource problem? is it gpu not powerful enough or is it some python package confliction happening here?

**Comment by nsalminen** [comment]
Hi @GitZinger, it's looking like your GPU does not have enough memory. As mentioned in the paper, I used two RTX 2080s for training, which each have 11 GB of VRAM. 

Firstly, you could consider decreasing the resolution of your images. Secondly, you could reduce the number of layers of the network, which will reduce the number of parameters and may allow training on your GPU. However, the performance of the model may worsen.

**Comment by GitZinger** [comment]
@nsalminen I really appreciate it. You are so kind.
You are using the Cuda 10 and cudnn 7.6? official doc says tf1.15 is up to these two version.

**Comment by nsalminen** [comment]
@GitZinger I'm happy to help! I don't have access to the original system I used, but as far as I can see in the TensorFlow documentation it should be CUDA 10 and cuDNN 7.4 ([source](https://www.tensorflow.org/install/source#tested_build_configurations)).
